{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kris-alpha.serviceAccountName" . }}
  labels:
    {{- include "kris-alpha.labels" . | nindent 4 }}
{{- end -}}
